### PR TITLE
Small fixed

### PR DESCRIPTION
**Pull request by TornaxO7**
- Bot shoul print the funny messages correctly when typing "rm"
- fixed version to 0.1.3

### CODE REVIEW

**Comment by MultisampledNight** [comment]
Already kind of done that, qwq.

**Comment by TornaxO7** [comment]
***Hmm intesifies***

**Comment by MultisampledNight** [comment]
***I totally don't know how it could happen that we are writing the same code, just don't look at the commit message***

**Comment by TornaxO7** [comment]
***I use Arch btw***

**Comment by MultisampledNight** [comment]
***Me too**

**Pull request closed without merging**
